### ISSUE TITLE
Unable to create test db using schema.sql

### ISSUE THREAD

**Issue by sway4em** [DegreePrerequisiteTracker/Degree-Prerequisite-Tracker#41]
Hey! I'm reviewing your project and ran into a small issue while setting up a test database in Supabase to try out your API. When I tried to run your schema.sql in the SQL Editor, I got this error:
```
ERROR:  42704: type "public.program_type" does not exist
LINE 21:     type public.program_type not null,
                  ^
```
Looks like there might be a missing enum type definition. Could you let me know:
- If there's a separate file for creating the custom types, or
- How you set up your test database when you were developing?

Thanks!

**Comment by Nathan-Lackie** [comment]
Good catch! We made a custom data type which we forgot to add to schema.sql
Will fix shortly, but you can run `CREATE TYPE program_type AS ENUM ('BS','BA','BFA','BArch','BLA')` to fix it.

**Comment by sway4em** [comment]
Thanks! FYI - https://supabase-schema.vercel.app/ can auto-generate your schema.sql. Might save you some time in the future!

**Comment by Nathan-Lackie** [comment]
Nice! Doesn't seem like that exports custom data types though, unfortunately.

Woah! But you can generate TypeScript types for your tables, that will definitely come in handy.
