### ISSUE TITLE
.env access

### ISSUE THREAD

**Issue by sway4em** [DegreePrerequisiteTracker/Degree-Prerequisite-Tracker#49]
Can I get access to your .env file so that I can interact with your production db?

**Comment by Nathan-Lackie** [comment]
You should be able to call our production database through our deployed render app at https://degree-prerequisite-tracker.onrender.com/.

If you want an env file to call your locally running app you can use this:
```
PGHOST="localhost"
PGDATABASE="postgres"
PGPORT=5432
PGUSER="postgres"
PGPASSWORD="password"

SUPABASEURL="https://eciuedmxxubiurblwicm.supabase.co"
SUPABASEKEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVjaXVlZG14eHViaXVyYmx3aWNtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mjk5Nzg4MzgsImV4cCI6MjA0NTU1NDgzOH0.4Yj5yja7Phb6880eMh46WyyNJSfaHNLaOhPvlNkzuHM"
```

Is there a use case I'm overlooking where you need access to our secrets? I'd be happy to provide any data you would need for review.
