### ISSUE TITLE
Code Review Comments (Connor Sullivan)

### ISSUE THREAD

**Issue by connor-ms** [DegreePrerequisiteTracker/Degree-Prerequisite-Tracker#50]
Hey! The code looks really good, and to be honest I struggled with finding any issues. I'm also not super familiar with TypeScript, so some of these might just be due to not understanding the syntax (mainly just for the 1st issue).

1. (maybe) SQL injection opportunities? In places like this:
https://github.com/DegreePrerequisiteTracker/Degree-Prerequisite-Tracker/blob/fa1aae716d9433621a885eba377c9980348a9bf2/src/api/departments.ts#L35
(just assuming based off of how it's done in Python)
2. Test data left in
https://github.com/DegreePrerequisiteTracker/Degree-Prerequisite-Tracker/blob/fa1aae716d9433621a885eba377c9980348a9bf2/src/api/users.ts#L8-L18
3. Another case
https://github.com/DegreePrerequisiteTracker/Degree-Prerequisite-Tracker/blob/fa1aae716d9433621a885eba377c9980348a9bf2/src/api/plans.ts#L99-L114
4. Missing initial data - it looks like there's some information that's required ahead of time to use this (such as course lists, programs/concentrations, and departments) but there's nothing supplied to initially populate this data.
5. Some inconsistent formatting, such as this:
https://github.com/DegreePrerequisiteTracker/Degree-Prerequisite-Tracker/blob/fa1aae716d9433621a885eba377c9980348a9bf2/src/api/programs.ts#L20
vs this:
https://github.com/DegreePrerequisiteTracker/Degree-Prerequisite-Tracker/blob/fa1aae716d9433621a885eba377c9980348a9bf2/src/api/programs.ts#L32-L34
6. Missing `plan/{plan_id}/courses` endpoint - the API spec mentions a way to retrieve the courses included in a plan, but there appears to be no implementation of it

Otherwise, everything looks really good!

**Comment by Nathan-Lackie** [comment]
Thanks for the review!
Just a quick note on the 1st comment, [Postgres.js uses tagged template literals in order to do parameter binding, which prevents SQL injection attacks](https://github.com/porsager/postgres?tab=readme-ov-file#queries).

**Comment by Nathan-Lackie** [comment]
2. https://github.com/DegreePrerequisiteTracker/Degree-Prerequisite-Tracker/issues/79
3. https://github.com/DegreePrerequisiteTracker/Degree-Prerequisite-Tracker/pull/74
4. This data is maintained in our database. Putting all this information in the schema.sql file would make it much too large. Scraper used to populate this date can be found at https://github.com/KaiiSnorlax/Catalog-Scraper
5. We use prettier to handle all of our formatting, it's not something we control manually
6. https://github.com/DegreePrerequisiteTracker/Degree-Prerequisite-Tracker/pull/74
