### ISSUE TITLE
Product Ideas (Connor Sullivan)

### ISSUE THREAD

**Issue by connor-ms** [DegreePrerequisiteTracker/Degree-Prerequisite-Tracker#52]
1. Add a way to bulk import previously finished courses, as it would be very time consuming to manually mark every completed course as "finished".
2. Add a feature to recommend which courses to take next, factoring in completed prereqs and expected graduation date.

**Comment by KaiSnorlax** [comment]
1. https://github.com/DegreePrerequisiteTracker/Degree-Prerequisite-Tracker/issues/85
2. This is a good idea, we have right now (https://github.com/DegreePrerequisiteTracker/Degree-Prerequisite-Tracker/pull/74) taking into account prereqs, but taking into account graduation date is interesting.
