### ISSUE TITLE
Code Review Comments (Eduardo Gallegos)

### ISSUE THREAD

**Issue by lalog12** [DegreePrerequisiteTracker/Degree-Prerequisite-Tracker#53]
Hi, great job on the group project! Everything looks great to me. Here are some nitpicks/mini problems. Overall, great job.

1. Static Implementation
https://github.com/DegreePrerequisiteTracker/Degree-Prerequisite-Tracker/blob/fa1aae716d9433621a885eba377c9980348a9bf2/src/api/users.ts#L14-L18

2. Static Implementation
https://github.com/DegreePrerequisiteTracker/Degree-Prerequisite-Tracker/blob/fa1aae716d9433621a885eba377c9980348a9bf2/src/api/users.ts#L8-L12

3. Static Implementation
https://github.com/DegreePrerequisiteTracker/Degree-Prerequisite-Tracker/blob/fa1aae716d9433621a885eba377c9980348a9bf2/src/api/plans.ts#L99-L114

4. No code comments

5. No Deletion Confirmation Message
https://github.com/DegreePrerequisiteTracker/Degree-Prerequisite-Tracker/blob/fa1aae716d9433621a885eba377c9980348a9bf2/src/api/users.ts#L28-L34

6. No Confirmation Message
https://github.com/DegreePrerequisiteTracker/Degree-Prerequisite-Tracker/blob/fa1aae716d9433621a885eba377c9980348a9bf2/src/api/users.ts#L24-L26

7. No Deletion Confirmation Message
https://github.com/DegreePrerequisiteTracker/Degree-Prerequisite-Tracker/blob/fa1aae716d9433621a885eba377c9980348a9bf2/src/api/plans.ts#L95-L96

8. No error handling for queries

9. Null handling?

10. Missing input validation for request bodies

11. No error logging

12. No timestamp fields

**Comment by KaiSnorlax** [comment]
1. https://github.com/DegreePrerequisiteTracker/Degree-Prerequisite-Tracker/issues/79
2. https://github.com/DegreePrerequisiteTracker/Degree-Prerequisite-Tracker/pull/80 
3. https://github.com/DegreePrerequisiteTracker/Degree-Prerequisite-Tracker/pull/74
5. No need, the 200 response code being sent back says that it is successful
6. No need, the 200 response code being sent back says that it is successful
7. No need, the 200 response code being sent back says that it is successful
8. https://github.com/DegreePrerequisiteTracker/Degree-Prerequisite-Tracker/issues/68 https://github.com/DegreePrerequisiteTracker/Degree-Prerequisite-Tracker/issues/82 https://github.com/DegreePrerequisiteTracker/Degree-Prerequisite-Tracker/issues/81 https://github.com/DegreePrerequisiteTracker/Degree-Prerequisite-Tracker/issues/69 https://github.com/DegreePrerequisiteTracker/Degree-Prerequisite-Tracker/issues/66
9. ^
10. https://github.com/DegreePrerequisiteTracker/Degree-Prerequisite-Tracker/issues/76
11. Errors will be logged in render
12.
