### ISSUE TITLE
Schema/API Design comments (Connor Sullivan)

### ISSUE THREAD

**Issue by connor-ms** [DegreePrerequisiteTracker/Degree-Prerequisite-Tracker#54]
1. `GET /subjects/{prefix}/course` - I think having the endpoint end with `courses` instead of `course` would be a bit clearer, as it can return multiple courses so a plural endpoint matches a bit better. This would also allow it match `GET /plan/{plan_id}/courses`.
2. `GET /course/{course_id}/` - I think having all `course` endpoints changed to `courses` would be clearer, as it's common practice to use a plural endpoint instead of singular.
3. `GET /program/*` - Same as above for the `program` endpoint.
4. `GET /plan/*` - Same as above for the `plan` endpoint.
5.`GET /program/{program_id}/BS/concentration/` & `GET /program/{program_id}/BS/concentration/{concentration_id}/` - it might make sense to remove the `/BS/` part and incorporate that information into the response data instead of including it in the endpoint, unless other information is provided under the `/BS/` directory.
6. In the above endpoints, `concentration` could be changed to `concentrations` for improved clarity and to follow common practice.
7. In APISpec.md, `POST /user/` only requires a username and email, but I think it would be helpful to include a password or password hash so no additional request is required to set a password.
8. `PUT /user/history/{course_id}` & `DELETE /user/history/{course_id}` - I think it would make more sense to change these to have `course_id` supplied in the data rather than the URL, and the URL's changed to just `/user/history`. This would also allow additional information to be added or removed if features in the future need it.

I couldn't find anything to comment on about the schema, as I think it looks very good. The api design looks great as well, and the only things I could find were more preferences than anything. Great job guys!

**Comment by KaiSnorlax** [comment]
1. https://github.com/DegreePrerequisiteTracker/Degree-Prerequisite-Tracker/issues/67
2. https://github.com/DegreePrerequisiteTracker/Degree-Prerequisite-Tracker/issues/67
3. https://github.com/DegreePrerequisiteTracker/Degree-Prerequisite-Tracker/issues/67
4. https://github.com/DegreePrerequisiteTracker/Degree-Prerequisite-Tracker/issues/67
5. https://github.com/DegreePrerequisiteTracker/Degree-Prerequisite-Tracker/issues/67
6. https://github.com/DegreePrerequisiteTracker/Degree-Prerequisite-Tracker/issues/67
7. Perhaps we will implement a separate endpoint to  put/delete multiple courses at once.
