### ISSUE TITLE
Product ideas (Libby Brill)

### ISSUE THREAD

**Issue by librill** [DegreePrerequisiteTracker/Degree-Prerequisite-Tracker#58]
1. Minors: having the option to view minors offered by each department, see the courses required, and add a minor to plans
2. Impact of adding/dropping classes: adding the option to see the potential impact of a given schedule plan on graduation date (given the number of courses already taken, what is the expected graduation date? how does that change as the planner is updated?)

**Comment by KaiSnorlax** [comment]
1. This is a good idea, but unfortunately for the scope of this project we only want to take into account bachelor degrees.
2. I like this idea, Im thinking it would be tied to the PUT/DELETE users/history/{courseId} endpoint.
