### ISSUE TITLE
Code Review Comments (Libby Brill)

### ISSUE THREAD

**Issue by librill** [DegreePrerequisiteTracker/Degree-Prerequisite-Tracker#59]
1. userID should be dynamic
https://github.com/DegreePrerequisiteTracker/Degree-Prerequisite-Tracker/blob/fa1aae716d9433621a885eba377c9980348a9bf2/src/api/users.ts#L8C1-L12C4

2. completedCourses should be dynamic
https://github.com/DegreePrerequisiteTracker/Degree-Prerequisite-Tracker/blob/fa1aae716d9433621a885eba377c9980348a9bf2/src/api/users.ts#L14C1-L18C4

3. variables should be dynamic
https://github.com/DegreePrerequisiteTracker/Degree-Prerequisite-Tracker/blob/fa1aae716d9433621a885eba377c9980348a9bf2/src/api/plans.ts#L99C1-L114C4

4. extra ":" with courses?
https://github.com/DegreePrerequisiteTracker/Degree-Prerequisite-Tracker/blob/fa1aae716d9433621a885eba377c9980348a9bf2/src/api/plans.ts#L99C1-L114C4

5. error handling for `one()` if the query does not return as expected (might not be an issue in typescript?)
https://github.com/DegreePrerequisiteTracker/Degree-Prerequisite-Tracker/blob/fa1aae716d9433621a885eba377c9980348a9bf2/src/api/subjects.ts#L29C1-L38C4

6. error handling if the given prefix does not exist (add a message)
https://github.com/DegreePrerequisiteTracker/Degree-Prerequisite-Tracker/blob/fa1aae716d9433621a885eba377c9980348a9bf2/src/api/subjects.ts#L29C1-L38C4

7. send message to user if "conflict" occurs
https://github.com/DegreePrerequisiteTracker/Degree-Prerequisite-Tracker/blob/fa1aae716d9433621a885eba377c9980348a9bf2/src/api/users.ts#L20C1-L26C4

8. add validation check (+ message if conflict) for courseID
https://github.com/DegreePrerequisiteTracker/Degree-Prerequisite-Tracker/blob/fa1aae716d9433621a885eba377c9980348a9bf2/src/api/users.ts#L28C1-L34C4

9. add validation check (+ message if conflict) for courseID
https://github.com/DegreePrerequisiteTracker/Degree-Prerequisite-Tracker/blob/fa1aae716d9433621a885eba377c9980348a9bf2/src/api/courses.ts#L14C1-L25C4

10. add validation check (+ message if conflict) for departmentID
https://github.com/DegreePrerequisiteTracker/Degree-Prerequisite-Tracker/blob/fa1aae716d9433621a885eba377c9980348a9bf2/src/api/departments.ts#L31C1-L42C4

11. overall, there should be more information communicated to the user (confirmation messages when creating/deleting plans, etc.)

12. add descriptive comments to code

**Comment by Nathan-Lackie** [comment]
1. https://github.com/DegreePrerequisiteTracker/Degree-Prerequisite-Tracker/pull/80
2. https://github.com/DegreePrerequisiteTracker/Degree-Prerequisite-Tracker/issues/79
3. https://github.com/DegreePrerequisiteTracker/Degree-Prerequisite-Tracker/pull/74
4. https://github.com/DegreePrerequisiteTracker/Degree-Prerequisite-Tracker/pull/74
5. https://github.com/DegreePrerequisiteTracker/Degree-Prerequisite-Tracker/issues/81
6. https://github.com/DegreePrerequisiteTracker/Degree-Prerequisite-Tracker/issues/81
7. No need, the 200 response code allows for that endpoint to be idempotent. That endpoint marks a course as complete, so if the course is already marked as completed, a 200 OK response should be returned.
8. Not planned, no need to validate course id
9. https://github.com/DegreePrerequisiteTracker/Degree-Prerequisite-Tracker/issues/68
10. https://github.com/DegreePrerequisiteTracker/Degree-Prerequisite-Tracker/issues/82
11. By virtue of the endpoint returning a 200 response code, that means that the request was a success, we do not need an explicit confirmation message.
