### ISSUE TITLE
Product Ideas (Swayam Chidrawar)

### ISSUE THREAD

**Issue by sway4em** [DegreePrerequisiteTracker/Degree-Prerequisite-Tracker#65]
1. Add a feature to recommend what classes to take next which also accounts for the fact that some courses are only offered during specific quarter
2. Add support for minors and double majors

**Comment by Nathan-Lackie** [comment]
1. Good idea, we plan on adding a "priority" feature which will rank courses based on how many other courses they are a prereq for
2. We want to add this, but out of scope for this class
