### ISSUE TITLE
Update APISpec.md

### ISSUE THREAD

**Issue by KaiSnorlax** [DegreePrerequisiteTracker/Degree-Prerequisite-Tracker#67]
https://github.com/DegreePrerequisiteTracker/Degree-Prerequisite-Tracker/blob/main/docs/APISpec.md

APISpec.md is outdated, use information from apiSpec.yml (these are endpoints that are fully implemented) to update.

**Comment by Nathan-Lackie** [comment]
We should use the docs page as our API spec, we don't really need the markdown file anymore
